### ISSUE TITLE
Platform name and version in package file name

### ISSUE THREAD

**Issue by szechyjs** [chef/omnibus#389]
It would be nice to have the platform name and version in the package filenames.

Example...

````
project-1.0.0-1.el5.x86_64.rpm
project-1.0.0-1.el6.x86_64.rpm
project-1.0.0-1.fc19.x86_64.rpm
project-1.0.0-1.fc20.x86_64.rpm
````

**Comment by johnbellone** [comment]
@schisamo Is it worth me readying a patch to fix this? This is causing us problems because community packages generally all follow this convention. Older versions of satellite rely on this information so that there are not clashes in the channels between Linux versions.

**Comment by johnbellone** [comment]
Using the last release of Chef 11 as an example:
```shell
~/Projects % rpm -qi -p chef-11.18.6-1.el6.x86_64.rpm 2>/dev/null |grep Release
Release     : 1.el6
```

**Comment by johnbellone** [comment]
This needs to be addressed. I understand that the RPM specification may not include "major version of Enterprise Linux" but it has clearly been a community standard for a long while. Your release team in fact *still* releases packages for Chef 11 using this convention. My assumption there is because your build pipeline is still using an older version of Omnibus.
