### ISSUE TITLE
Skeleton OSX postinstall scripts should be included and documented

### ISSUE THREAD

**Issue by sebbacon** [chef/omnibus#407]
This is a difficult bug for me to write well as I don't have OSX.

I would like my installer to add a symlink my software in `/usr/bin/`.  For Debian I edit the supplied `postinst` at `package-scripts/$PROJECT_NAME/postinst`.

According to the occasional blog post around the internet ([example](https://tickets.opscode.com/browse/CHEF-4479)), the equivalent for OSX is `package-scripts/$PROJECT_NAME/makeselfinst`. However, packages I've asked people to build are not executing this file on install. (Confusingly, the example linked to above states that it _is_ executed on 10.8.4).

Looking through the source code, I don't see any evidence that `makeselfinst` is ever used for an OSX build.  Instead, I [see](https://github.com/opscode/omnibus/blob/e1dd9cde1d21f2aae06a4cdef98e36c852f8d143/spec/unit/packagers/pkg_spec.rb#L114) that the entire `package-scripts` directory is passed through to OSX's `pkgbuild` command with the `--scripts` argument.  The [man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/pkgbuild.1.html) for `pkgbuild` has this to say:

```
 --scripts scripts-path
             Archive the entire contents of scripts-path as the package scripts. If this directory con-tains contains
             tains scripts named preinstall and/or postinstall, these will be run as the top-level
             scripts of the package. If you want to run scripts for specific bundles, you must specify
             those in a component property list; see more at COMPONENT PROPERTY LIST.  Any other files
             under scripts-path will be used only if the top-level or component-specific scripts invoke
             them.
```

Therefore, it seems to me that the skeleton resources required for OSX pre/post installation are copies of the `preinst` and `postinst` Debian files, renamed to `preinstall` and `postinstall` respectively.

If this is correct, it should also be mentioned in the OSX-specific documentation, and the `postinst` and `preinst` on Debian.

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
