### ISSUE TITLE
How to use system libraries in omnibus?

### ISSUE THREAD

**Issue by repeatedly** [chef/omnibus#412]
Is this possible?
We use omnibus for td-agent package and we want to use system library, e.g. openssl.
There are several reasons:

- If openssl has a bug, releasing new package is needed. If Ruby's openssl depends on system library, updating system package is enough.
- Some users try to install gem package via omnibus gem and gem sometimes requires system libraries.

I found https://tickets.opscode.com/browse/COOK-1406 issue but the solution not found.
I tried to remove `dependency 'openssl'` from ruby software, but health checker rejects some links by 'Unsafe dependency'.

How to handle this problem? Is there good solution or guide?

**Comment by PierreRambaud** [comment]
Hi,
If someone have an idea or find something, I'm very interesting, I curently trying to compile a gtk app and it's really hard to add all dependencies such as X11, radeon, nouveau, etc...
Regards

**Comment by cboggs** [comment]
I believe your best bet would be to whitelist the files that depend on openssl libraries, via:
whitelist_file "bin/my_binary"

That will tell Omnibus to ignore unsafe conditions on whatever file resides at #{relative_path}/bin/my_binary, as I understand it.

**Comment by lamont-granquist** [comment]
The design goal of omnibus is a build system to package all the dependencies of a piece of software outside of a limited set of very core system libraries.   The whole point is that we want to ship a consistent ruby and link against a consistent openssl version, etc.  You can add to the whitelists, but it starts to defeat the original purpose.

**Comment by cboggs** [comment]
I did indeed forget to mention that whitelisted files should be EXCEEDINGLY rare.

To @lamont-granquist's point, whitelisting anything implies that you have incredibly strict control over the versions of stuff that's installed on all your systems that might get your Omnibus package installed - and if that's the case, then there's not much point in using Omnibus. :-)

**Comment by lamont-granquist** [comment]
Yeah, I'm kind of puzzled at some requests like this where it seems like we haven't clearly described what omnibus really is designed to do.  It isn't an all purpose cross platform packaging system that everyone should use (at least not right now).  It solves a real specific purpose which is to port apps to a wide variety of different vendor platforms bundled with literally all of their dependencies to work around completely intractable distro support issues.  If you don't have those distro support issues and don't care about things like CentOS 5.x then you probably shouldn't be using this.

But that's not to say it couldn't grow into something bigger, since there's clearly demand for something out there, I'm just not sure what problem people are looking at omnibus to solve where its failing.

**Comment by salsa-dev** [comment]
@lamont-granquist This is exactly the point one fails to understand when starting to use omnibus. Thanks for clearing it out.

**Comment by lamont-granquist** [comment]
looks like this can be closed

**Comment by repeatedly** [comment]
Ah, sorry. I should have closed this issue.
Thanks for the clarification :)
