### ISSUE TITLE
Error in revision_from_remote_reference

### ISSUE THREAD

**Issue by szechyjs** [chef/omnibus#426]
I've been getting a lot of these errors lately with v4.0.0 and master.

```
Could not resolve `1.3.0' to a valid git SHA-1.

/home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/fetchers/git_fetcher.rb:189:in `revision_from_remote_reference'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/fetchers/git_fetcher.rb:152:in `target_revision'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/fetchers/git_fetcher.rb:162:in `same_revision?'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/fetchers/git_fetcher.rb:26:in `fetch_required?'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/software.rb:593:in `fetch'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/project.rb:919:in `block (3 levels) in build_me'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/thread_pool.rb:64:in `call'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/thread_pool.rb:62:in `loop'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/thread_pool.rb:61:in `catch'
  /home/omnibus/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
```

The only way I get around it is to go in and delete the src directory for the software that is pulling from the git repo in the cache directory.

the 1.3.0 branch existed the previous time I ran the build and it worked fine. The only thing that changed in this build is that I switched branches in my omnibus project. The changes in this branch do not even affect the software project that fails to find the git tag.

**Comment by szechyjs** [comment]
I think I've actually identified the source of the problem...

The tag that it is trying to pull has changed. At some point the original tag was deleted and re-added to a new commit.

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
