### ISSUE TITLE
Omnibus::Builder::copy doesn't error out on failure

### ISSUE THREAD

**Issue by SarahRiley** [chef/omnibus#432]
While trying to build flapjack, I tried using copy on a non-existant file.  This didn't result in an error, but it seems like it should.

```
                   [Builder: redis] I | copy `dist/etc/redis/asdfsdaf' to `/opt/flapjack/embedded/etc/redis/': 0.0023s
```

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
