### ISSUE TITLE
Reexamining Debian package naming

### ISSUE THREAD

**Issue by whiteley** [chef/omnibus#442]
Once again, I am encountering unintended consequences from the well meaning and often discussed https://github.com/chef/omnibus/pull/88. I just created https://github.com/chef/chef-provisioning/issues/305 to deal with package name collisions of Chef client debs.

This was recently addressed with an [improvement for rpm packages](https://github.com/chef/omnibus/commit/0536e5567f25ecd4588ac575073e4ef4959eba64) and accepted on the merit of the very same arguments myself and others made in the original conversation.
1. Matching conventions
2. Supporting common tools and use cases

Due to the `pool/` directory convention in many APT repository tools, it is common by upstream packagers to use the identical package for more than one release where possible and when incompatible to insert the release version into the package name. A couple of random examples I pulled from a mirror:

```
icedtea-7-jre-jamvm_7u75-2.5.4-1~trusty1_amd64.deb
icedtea-7-jre-jamvm_7u75-2.5.4-1~utopic1_amd64.deb
libdrm2_2.4.52-1~precise2_amd64.deb
libdrm2_2.4.52-1~saucy1_amd64.deb
```

```
a2ps_4.14-1.1+deb6u1_amd64.deb
a2ps_4.14-1.1+deb7u1_amd64.deb
xbuffy_3.3.bl.3.dfsg-8+deb6u1_amd64.deb
xbuffy_3.3.bl.3.dfsg-8+deb7u1_amd64.deb
```

and just to show that many more examples exist:

```
$ find ubuntu/pool -type f -regex '.*\(lucid\|precise\|saucy\|trusty\|utopic\|vivid\)[0-9]*_amd64\.deb' -print | wc -l
1409
$ find debian/pool -type f -regex '.*deb[0-9]*u[0-9]*_amd64.deb' -print | wc -l
2401
```

I don't understand the resistance to this since it's clearly an issue for some folks and as far as I can tell only produces slightly longer filenames for anyone else and ask that this decision be reexamined.

Thank you!

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
