### ISSUE TITLE
A knob to make caching less conservative would be super helpful

### ISSUE THREAD

**Issue by randomcamel** [chef/omnibus#468]
I'm trying to learn Omnibus, but the cycle time is long because it regularly (and unpredictably, from a user perspective) recompiles all its dependencies: ncurses, openssl, Ruby, the whole works, which means it can take 15 minutes to find out I did the wrong thing (when, for example, all I'm trying to do is install a gem).

Some kind of setting to limit the recompiling would go a long way toward making it easier for new people to learn to use Omnibus (which in turn means less work for the people who already know it). This could take the form of specifically whitelisting things to not be recompiled, or something else; anything would help.

**Comment by stevendanna** [comment]
@randomcamel The most common cause of having all the dependencies changed is a change to the project file itself.  The content of the project file is part of the cache key, so changing it requires a full rebuild.

Not a solution to this request, just hopefully sheds some light on what is going on.

**Comment by schisamo** [comment]
@randomcamel You should also place your most frequently changed components at the bottom of the dep list, for example:
https://github.com/chef/opscode-omnibus/blob/master/config/projects/chef-server.rb#L83-L94

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
