### ISSUE TITLE
`omnibus-software` should be included in Gemfile by default

### ISSUE THREAD

**Issue by dblessing** [chef/omnibus#471]
Related to #361 

If the default software configuration has things like `preparation` included by default then the Gemfile should also have `omnibus-software` uncommented by default so standard default builds work. Otherwise Omnibus project builds fail OOTB.

**Comment by stevendanna** [comment]
I think we should actually move in the other direction.  Include a preparation DSL method at the project level  and remove the need for the dependnecy.

**Comment by schisamo** [comment]
:+1: to what @stevendanna said.

**Comment by yzl** [comment]
@stevendanna I am +1 with a preparation DSL method as well.

**Comment by dblessing** [comment]
Sure that's fine. Anything that ultimately leads to things working OOTB :)

**Comment by alainchiasson** [comment]
Has anything changed on this ? The latest omnibus still fails OOTB and noticed that the `omnibus-software` Gem is not in rubygems. omnibus-chef places the following in the `Gemfile` : 

```
gem 'omnibus-software', github: 'chef/omnibus-software'
```

Is this the workaround until this is resolved ?

**Comment by schisamo** [comment]
@alainchiasson Assuming there is no `#` at the start of that line `bundle install` should pull in omnibus-software from the GitHub repo properly.

**Comment by davidcpell** [comment]
I ran into the issue in #361 today and am now here trying to track the course of this issue over the past few years. Adding 'gem 'omnibus-software', github: 'chef/omnibus-software'' seemed to resolve the initial problem that I had (being able to find "preparation" software when running `bin/omnibus build PROJECT`).

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
