### ISSUE TITLE
Support for build channels

### ISSUE THREAD

**Issue by jaym** [chef/omnibus#507]
Whenever I want to do a release, I find myself modifying the override dependencies in my project file. This is annoying because I need to remember to change these back to floating values so that nightlies builds do the right thing and float on master. I'm proposing we add a construct that makes this easier:

I don't know if channels is the right word here, but I'd like to have some sort of build context blocks in the DSL so that dependencies (and basically anything else) can be context dependent. Some possible contexts would be dev, nightly, and release.

A sample project config I'm thinking of:

``` ruby
name "chef"
friendly_name "Chef Client"
maintainer "Chef Software, Inc. <maintainers@chef.io>"
homepage "https://www.chef.io"

build_iteration 1
build_version do
  source :git, from_dependency: 'chef'
  output_format :semver
end

dependency "preparation"
dependency "chef"
dependency "version-manifest"

override :rubygems,       version: "2.4.4"

package :rpm

package :pkg do
  identifier "com.getchef.pkg.chef"
end
compress :dmg

channel :dev do
  override :rubygems, "dansrubygemshack"
end

channel :nightly do
  override :chef, "master"
  override :rubygems, "master"
end

channel :release do
  override :chef, "12.x.x"
  pacakge :rpm do
      signing_passphrase ENV['OMNIBUS_RPM_SIGNING_PASSPHRASE']
  end

  package :pkg do
      signing_identity "Developer ID Installer: Chef Software, Inc. (EU3VF8YLX2)"
  end
end
```

In this case, nightlies are set to follow master. You can pin release versions in the code, and commit that without disturbing nightlies. Release pacakges are the only ones that get signed. The omnibus cli could have a flag that lets you set the channel when building.

**Comment by szechyjs** [comment]
:+1: love this idea. Right now I'm handling this by creating multiple branches of my omnibus project. One branch follows master branches, and the others use pinned versions.

**Comment by adamleff** [comment]
I'm so :+1: on this idea.  Maybe "pipeline" or "build_pipeline" instead of "channel"?  Either way, this is a great idea.

**Comment by lamont-granquist** [comment]
Yes, i hate branches :+1:

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
