### ISSUE TITLE
cache population seems to assume that any checksum is an md5

### ISSUE THREAD

**Issue by thommay** [chef/omnibus#529]
```
source url: "http://slproweb.com/download/Win64OpenSSL-1_0_1p.exe", sha256: "e8d3b76bcc43781b38328431901c8f64b7e86b37002ae4841a663c44889c8d2f"
```

This should really blow up because I've not provided an md5, but we try to use the sha256 as an md5 and sadness breaks out all round:

```
 [S3Cache] I | Caching './local/cache/Win64OpenSSL-1_0_1p.exe' to 'opscode-omnibus-cache/delivery-windows-openssl-1.0.1p-e8d3b76bcc43781b38328431901c8f64b7e86b37002ae4841a663c44889c8d2f'
Digest::Digest is deprecated; use Digest
/Users/thom/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/uber-s3-0.2.4/lib/uber-s3/response.rb:37:in `success?': BadDigest: The Content-MD5 you specified did not match what we received. (UberS3::Error::BadDigest)
```

**Comment by szechyjs** [comment]
What version of omnibus are you using? I believe the sha sums feature has not yet been released.

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
