### ISSUE TITLE
Document that building with omnibus requires git version > 1.7.7

### ISSUE THREAD

**Issue by mattray** [chef/omnibus#544]
When attempting to build on Wind River Linux 5 and pass an OHAI_VERSION from the CLI the build blows up with

[PathFetcher: openssl-customization] I | Digesting /root/omnibus-chef/files/openssl-customization with sha256
                 [GitFetcher: ohai] I | Fetching from `git://github.com/chef/ohai'
                 [GitFetcher: chef] I | Fetching from`git://github.com/chef/chef'
The following shell command exited with status 128:

```
$ git fetch git://github.com/chef/ohai v8.6.0
```

I upgraded to git 2.4.1 and the build works fine.

**Comment by schisamo** [comment]
The assumption is any build mode setup will be done using the Omnibus cookbook.  Obviously that doesn't work for platforms we yet to have a chef-client for!

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
