### ISSUE TITLE
Using custom ruby gems source

### ISSUE THREAD

**Issue by iroller** [chef/omnibus#546]
That's more of a question, sorry for posting it as an issue.

What's the best way of providing omnibus with an additional custom gem source?

I'm using test-kitchen and tried adding ~/.gemrc for vagrant user but omnibus doesn't look into it and still fails not being able to find one of software dependencies being in a private gem repo.

**Comment by danielsdeleo** [comment]
gemrc seems like the way to go, are you sure the user omnibus is running as is the same as the one whose gemrc you configured?

I don't know if bundler will use a gemrc, but you can configure a mirror for it (I don't remember exactly how, but it's documented in the `bundle install` manpage IIRC).

**Comment by iroller** [comment]
Yes, I'm sure about the user.
Bundler doesn't look into .gemrc.

However we can use per-gem source in Gemfile:
```
source 'https://rubygems.org'

gem 'common'
gem 'custom', source: "https://custom.repo.com"
```

And configure credentials using `bundle config custom.repo.com user:password`.

Can I somehow implement it in software definition? I see that "source" can be git, url and path. Should it be configured somewhere else?

Thanks for your help :+1:

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
