### ISSUE TITLE
Rebar software definition no longer works

### ISSUE THREAD

**Issue by oferrigni** [chef/omnibus#594]
@chef/engineering-services 

The rebar software definition fails when used with https://github.com/chef/omnibus/commit/58f4b2622adc524aa7bd8a369938a0ea44aaf3aa . When name and relative_path are both set, the copy command fails trying to copy a binary from "rebar/rebar/rebar" where rebar is the project_name and the relative_path and the binary to copy. This functionality was working as of https://github.com/chef/omnibus/commit/c078b22c0b77b96b00e4f529af7466c919d25529 .

Reviewing the code, it appears https://github.com/chef/omnibus/pull/584/files may contain the breaking change. There are 7 software definitions that are impacted.

config/software/cacerts.rb
config/software/figlet-fonts.rb
config/software/nrpe.rb
config/software/pkg-config.rb
config/software/rebar.rb
config/software/relx.rb
config/software/runit.rb

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
