### ISSUE TITLE
Clone and trying to run the unit tests

### ISSUE THREAD

**Issue by cpanato** [chef/omnibus#606]
Hello
I clone the repo and I'm trying to run the unit test but I'm getting one error.
After the clone I did the bundle install and after the bundle exec rake unit but got an errror

```
/Users/test/.rubies/ruby-2.1.5/bin/ruby -I/Users/test/.gem/ruby/2.1.5/gems/rspec-core-3.4.1/lib:/Users/test/.gem/ruby/2.1.5/gems/rspec-support-3.4.1/lib /Users/test/.gem/ruby/2.1.5/gems/rspec-core-3.4.1/exe/rspec --pattern spec/unit/\*\*/\*_spec.rb --color --format progress failed
rake aborted!
TypeError: no implicit conversion from nil to integer
/Users/test/.gem/ruby/2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/rake_task.rb:84:in `exit'
/Users/test/.gem/ruby/2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/rake_task.rb:84:in `run_task'
/Users/test/.gem/ruby/2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/rake_task.rb:96:in `block (2 levels) in define'
/Users/test/.gem/ruby/2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/rake_task.rb:94:in `block in define'
Tasks: TOP => unit
```

there are anything I need do before run?
thanks!

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
