### ISSUE TITLE
"Could not locate or access the package at the given path" on centos7

### ISSUE THREAD

**Issue by gilzellner** [chef/omnibus#682]
### Description

"Could not locate or access the package at the given path" on centos7
Happens sporadically.
### Omnibus Version

Tell us which version of Omnibus you are using
### Platform Version

Centos7 on AWS
### Replication Case

I've tried to create a small scale replication but was unable to do that.
Since our software is open source anyway you can simply run it.
the ami has omnibus pre-installed to save creation time but is otherwise vanilla centos 

set these env vars:
AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']
git clone git@github.com:cloudify-cosmo/cloudify-manager.git
cd cloudify-manager
git checkout CFY-5210-move-restservice-packaging-to-omnibus
cd packaging
vagrant up 
### Build Output

```
16:09:11 ==> restservice: Could not locate or access the package at the given path:
16:09:11 ==> restservice: 
16:09:11 ==> restservice:     /tmp/pkg/rest-service-3.4.0~m5-394.el7.x86_64.rpm
16:09:11 ==> restservice: 
16:09:11 ==> restservice: /home/ec2-user/.rvm/gems/ruby-2.3.0/gems/omnibus-4.1.0/lib/omnibus/metadata.rb:39:in `generate'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/gems/omnibus-4.1.0/lib/omnibus/packagers/base.rb:147:in `run!'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/gems/omnibus-4.1.0/lib/omnibus/project.rb:1062:in `package_me'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/gems/omnibus-4.1.0/lib/omnibus/project.rb:1012:in `build'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/gems/omnibus-4.1.0/lib/omnibus/cli.rb:83:in `build'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/gems/omnibus-4.1.0/lib/omnibus/cli/base.rb:33:in `dispatch'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/gems/omnibus-4.1.0/lib/omnibus/cli.rb:41:in `execute!'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/gems/omnibus-4.1.0/bin/omnibus:11:in `<top (required)>'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/bin/omnibus:23:in `load'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/bin/omnibus:23:in `<main>'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
16:09:11 ==> restservice:   /home/ec2-user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

---

/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
