### ISSUE TITLE
Licensing and versioning fail when software sources aren't cleaned

### ISSUE THREAD

**Issue by krallin** [chef/omnibus#683]
### Description

When restoring a build from cache, licensing and versioning will (silently) fail if software sources haven't been cleaned.

Specifically:
- License files will not be found (because the sources have never been cleaned and therefore nothing has been extracted). This will be reported in the logs with plenty of log files not being found.
- Using `build_version {  source :git, from_dependency: '...' }` may return the _wrong_ version because the desired tag has never been checked out. No error will be reported in the logs here, but the version will be incorrect.

A reasonably simple solution is to ensure that software sources are always cleaned (I'm using a crappy monkey-patch to do this: https://github.com/aptible/omnibus-aptible-toolbelt/pull/7, but it's not ideal since I end up cleaning twice — an in-tree solution could easily avoid that).

Another solution might be to include the build output in the cache dir (or the metadata), or to crash (instead of failing silently) if the cache is present but the build dir isn't.
### Omnibus Version

`5.4.0`
### Platform Version

OSX, CentOS 6, CentOS 7, Ubuntu 14.04, Ubuntu 16.04, Debian 7, Debian 8.
### Replication Case

Create a new project with a git dependency that targets a tag that isn't the most recent one and set the version `from_dependency` to that dependency.

Then, build. Package version will be that of the dependency (correct).

Then, remove the `build` dir, but not the git cache dir.

Then, build again. Package version will be the most recent one (incorrect).
### Build Output

https://travis-ci.org/aptible/omnibus-aptible-toolbelt/jobs/133519557

Observe version `v0.6.8` of `aptible-cli` being built, and yet the package version ends up being `v0.6.9`. Also observe all license files reported as missing.

---

/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

(FYI: the above ping was in the issue template, but I don't think I can ping a `@chef` team without being a `@chef` member).

**Comment by sersut** [comment]
Thanks for reporting this @krallin. I am leaning towards option (1) since the source files can be used for versioning / licensing and potentially other things in the future.

**Comment by zdavis** [comment]
Running into the same problem and will attempt a PR to address this.

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
