### ISSUE TITLE
Can't escape spaces in windows paths

### ISSUE THREAD

**Issue by thomaslitton** [chef/omnibus#685]
### Description

install_dir "C:/Program\ Files\ (x86)/watcher" is translated to C:/Program/ Files/ (x86)/watcher/ which causes build failures:

Output:
    gcc -IC:/Program/ Files/ (x86)/watcher/embedded/include -m32 -O3 -march=i686 -Wall -c -o adler32.o adler32.c
Error:
    /bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0:`gcc -IC:/Program/ Files/ (x86)/watcher/embedded/include -m32 -O3 -march=i686 -Wall -c -o adler32.o adler32.c'
make: **\* [adler32.o] Error 2
### Omnibus Version

5.4.0
### Platform Version

Windows

**Comment by ksubrama** [comment]
Yep - it's a known issue.  We don't support spaces in paths when it involves msys/mingw tooling because there are way too many places where path translations occur and the posix compatibility layer in place doesn't handle it uniformly in all situations.  The only current workaround is to not pull install_dir or any part of the windows compiler toolchain in any path that has a space in it.

**Comment by jaspergould** [comment]
GOOOD.

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
