### ISSUE TITLE
chef missing dependency on coreutils

### ISSUE THREAD

**Issue by swimfrog** [chef/omnibus#755]
### Description

When installing chef RPM via anaconda installer using kickstart, chef can be installed before "coreutils" package, which contains many basic binaries such as basename, uname, rm, etc. This causes the post-install script to fail, which results in some of the /usr/bin symlinks failing to be created, and may cause other problems. This generates a warning during kickstart, so if the error is not noticed, the chef installation might not be correct.

The RHEL/CentOS anaconda installer orders packages based on depsolving. I think it's likely that adding an explicit dependency on "coreutils", or the binaries that it provides would solve this problem.

Anaconda output:

```
Installing chef-12.9.38-1.el6.x86_64
warning: chef-12.9.38-1.el6.x86_64: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
/var/tmp/rpm-tmp.GmMCvA: line 13: basename: command not found
/var/tmp/rpm-tmp.GmMCvA: line 31: uname: command not found
/var/tmp/rpm-tmp.GmMCvA: line 26: uname: command not found
/var/tmp/rpm-tmp.GmMCvA: line 58: expr: command not found
/var/tmp/rpm-tmp.GmMCvA: line 83: rm: command not found
/var/tmp/rpm-tmp.GmMCvA: line 84: rm: command not found
/var/tmp/rpm-tmp.GmMCvA: line 85: rm: command not found
/var/tmp/rpm-tmp.GmMCvA: line 86: rm: command not found
/var/tmp/rpm-tmp.GmMCvA: line 87: rm: command not found
/var/tmp/rpm-tmp.GmMCvA: line 88: rm: command not found
/var/tmp/rpm-tmp.GmMCvA: line 90: ln: command not found
: Cannot link chef-solo to /usr/bin
warning: %post(chef-12.9.38-1.el6.x86_64) scriptlet failed, exit status 1
```

### Omnibus Version

12.9.38-1.el6

(I glanced through the code and compared dependencies and scripts with the latest RPM, and it seems likely that this would still be an issue with the latest RPM, but I can't use it in my lab, so I haven't tested with later RPMs)

### Platform Version

RHEL6

### Replication Case

Create a kickstart that:
* References a custom yum repo containing a chef RPM, in addition to base packages on CDROM or other yum repo.
* Has a package list containing chef, among other base install packages

### Build Output

N/A

--------------------------------------------------
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
