### ISSUE TITLE
Problem on building with Omnibus

### ISSUE THREAD

**Issue by LionsWrath** [chef/omnibus#802]
### Description

I have been trying to use Omnibus for some days now,  but I always end up with some problem, mostly related with the fact that I don't know how the Omnibus works. So, I created this issue to ask some questions (Noob ones). Sorry if this isn't the right place to ask.

### Omnibus Version

v5.6.1

### Platform Version

I am using Ubuntu 16.04.3 LTS (xenial), x86_64

#### Creating a DEB

When creating a DEB installer, where do I put the usual configuration that programs like **dh_make** create? How do I put configuration of usual files like **rules**, **dirs**, **control**, **changelog** and **projectname.install**? I understand that most meta configuration stays in folder **projects/projectname.rb**.

#### Building the DEB

Where is the right place to put the sources of the program? Considering that it is a simple C++ program
with dependencies with two libraries, how do I build them? I have to use a dependency command to compile it separately? And after compiling, where do I put the executable to be put inside the DEB?

#### Building dependencies

When creating software dependencies for the program, I have to download the source and compile every time? Or it is possible to install using package managers like **apt** for linux?

#### Clean chroot

There is any way to create a DEB using a clean **chroot** installation like **pdebuilder** do for testing purposes?

#### Base directory

What is the difference in using the local configuration and the default system folders? Why do the process of creating a DEB uses installation directories?

#### Healthcheck

How does **whitelisting** and **healthcheck** works? When I compiled and tried to move a executable to the **install_dir**, I got an healthcheck error.

#### Versioning

How do I set Omnibus to take care of the versioning?

--------------------------------------------------

**Comment by danielsdeleo** [comment]
For informational questions like this, we generally use the discourse/mailing list thing here: https://discourse.chef.io or our community slack for real-time interactions: https://community-slack.chef.io

To answer your questions, it's important to lay out some of the general principles of omnibus. Omnibus is designed to allow you to consistently build and deliver complex applications like Chef, Chef Server, etc. in an end-user-friendly way across multiple platforms. To achieve this, omnibus requires you to build the full stack of your application, including all dependencies above libc. While this means you will be duplicating a lot of things your distro provides, such as zlib, openssl, etc., you control the version of all of these things and don't have to worry about what version is available for CentOS 5 vs. Ubuntu 16 and so on. By understanding this, we can answer a few of your questions:

* Dependencies: you have to specify all of your dependencies in your project and software definitions so they will get built in to your package
* Compiling dependencies: There is a git-based cache system that can cache some parts of the build. Unfortunately, because we don't place too many restrictions on how things get built, the cache gets invalidated more frequently than we would like. If you just need really fast builds and only target linux, then you could look into habitat which makes some different design choices that allow it to rebuild a lot less of the stack.
* Health check: healthcheck runs `ldd` to make sure you are not accidentally depending on software that may not be installed (or might be a different version) on the end-user's machine when they install the package
* Extra deb features: Omnibus focuses mostly on using a least-common-denominator subset of the functionality for each package manager. So it works similarly to the `fpm` project in that it only exposes the essential functionality and in general abstracts the details of the package manager. We handle things like changelogs outside of the debian packaging system.
* chroot builds: the various packaging systems we target don't all support chroot builds, so we're unable to use this feature, though it would be preferable.

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
