### ISSUE TITLE
Before building in vagrant sourcing of load-omnibus-toolchain.sh is required

### ISSUE THREAD

**Issue by raags** [chef/omnibus#807]
### Description

Document that building in vagrant also requires sourcing the `load-omnibus-toolchain.sh` script. 

Without sourcing bundler or build failures can occur due to inconsistent dependency or library versions. Or, let the omnibus cookbook add a file in profile.d to source this file.

### Omnibus Version

5.6.1

### Platform Version

Ubuntu Trusty 14.04

### Replication Case

Run kitchen converge on Ubuntu Trusty platform. The Readme specifies logging in and just running `bin/omnibus build <pkg>` but this may fail until `load-omnibus-toolchain.sh` script is sourced.

The `bundle install` step before this may also fail due to older ruby version, libraries, etc

--------------------------------------------------

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
